defaults:
  - alg: mappo_objectives_capture
  - _self_

# experiment params
NUM_SEEDS: 1
SEED: 0

# wandb params
ENTITY: ""
PROJECT: "simple-tag-objectives"
WANDB_MODE: "disabled"

# where to save the params
SAVE_PATH: "logs"
